version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region eu-west-3)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd Frontend && docker build -t 811661224836.dkr.ecr.eu-west-3.amazonaws.com/code-build:my-frontend-image .
      - cd ../Backend && docker build -t 811661224836.dkr.ecr.eu-west-3.amazonaws.com/code-build:my-api-image .
      - cd ../database && docker build -t 811661224836.dkr.ecr.eu-west-3.amazonaws.com/code-build:my-database-image .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 811661224836.dkr.ecr.eu-west-3.amazonaws.com/code-build:my-frontend-image
      - docker push 811661224836.dkr.ecr.eu-west-3.amazonaws.com/code-build:my-api-image
      - docker push 811661224836.dkr.ecr.eu-west-3.amazonaws.com/code-build:my-database-image
      - echo Writing image definitions file...
      - printf '[{"name":"frontend-container","imageUri":"%s"},{"name":"api-container","imageUri":"%s"},{"name":"database-container","imageUri":"%s"}]' my-frontend-image my-api-image my-database-image > imagedefinitions.json

artifacts:
  files: imagedefinitions.json