version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region eu-west-3)

  build:
    commands:
      - echo Building the Docker image for the API...
      - docker build -t api-image ./Backend
      - docker tag api-image:latest 811661224836.dkr.ecr.eu-west-3.amazonaws.com/code-build:api-image

      - echo Building the Docker image for the Frontend...
      - docker build -t frontend-image ./Frontend
      - docker tag frontend-image:latest 811661224836.dkr.ecr.eu-west-3.amazonaws.com/code-build:front-image

      - echo Building the Docker image for the Database...
      - docker build -t database-image ./database
      - docker tag database-image:latest 811661224836.dkr.ecr.eu-west-3.amazonaws.com/code-build:database-image

  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push 811661224836.dkr.ecr.eu-west-3.amazonaws.com/code-build:api-image
      - docker push 811661224836.dkr.ecr.eu-west-3.amazonaws.com/code-build:front-image
      - docker push 811661224836.dkr.ecr.eu-west-3.amazonaws.com/code-build:database-image
      - echo Writing image definitions file...
      - printf '[{"name":"api-container","imageUri":"123456789012.dkr.ecr.%s.amazonaws.com/my-api-repo:latest"},{"name":"frontend-container","imageUri":"123456789012.dkr.ecr.%s.amazonaws.com/my-frontend-repo:latest"},{"name":"database-container","imageUri":"123456789012.dkr.ecr.%s.amazonaws.com/my-database-repo:latest"}]' $AWS_DEFAULT_REGION $AWS_DEFAULT_REGION $AWS_DEFAULT_REGION > imagedefinitions.json
