name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d_%H:%M:%S')" >> $GITHUB_ENV
      - name: Build frontend image
        run: cd Frontend && docker build -t front-image .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: julesdavoust
          password: 17075Kayo_#2002!
      - name: Push frontend image
        run: |
          docker tag front-image julesdavoust/front-image:${{ env.TIMESTAMP }}
          docker images
          docker push julesdavoust/front-image:${{ env.TIMESTAMP }}
        

  # build-api:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Build the API image
  #       run: cd Backend && docker build -t api-image .
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: julesdavoust
  #         password: 17075Kayo_#2002!
  #     - name: Push API image
  #       run: |
  #         docker tag api-image julesdavoust/api-image:$(date +%s)
  #         docker push julesdavoust/api-image:$(date +%s)

  # build-database:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Build the database image
  #       run: cd database && docker build -t bdd-image .
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: julesdavoust
  #         password: 17075Kayo_#2002!
  #     - name: Push database image
  #       run: |
  #         docker tag bdd-image julesdavoust/bdd-image:latest
  #         docker push julesdavoust/bdd-image:latest
